spring:
  application:
    name: auth-service

# Eureka — usa el nombre del servicio Docker, no localhost
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/
#    # Reducir agresividad de reintentos al inicio
#    initial-instance-info-replication-interval-seconds: 20
#    registry-fetch-interval-seconds: 15
#  instance:
#    prefer-ip-address: true
#    # Heartbeat y lease más tolerantes durante el arranque
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30


logging:
  level:
    com.diegoanyosa.authservice: DEBUG
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN
    org.springframework.cloud.config: WARN
    org.springframework.security: DEBUG
    org.springframework.validation: DEBUG

